[package]
name = "tempfile"
version = "0.4.0"
authors = ["Steven Allen <steven@stebalien.com>"]
description = "Securely create temporary files."

documentation = "https://stebalien.github.io/tempfile/tempfile/"
repository = "https://github.com/Stebalien/tempfile"
keywords = ["tempfile", "tmpfile"]
license = "MIT/Apache-2.0"

[dependencies]
libc = "*"
rand = "*"

[target.x86_64-pc-windows-gnu.dependencies]
winapi = "*"
kernel32-sys = "*"

[target.i686-pc-windows-gnu.dependencies]
kernel32-sys = "*"
