[package]
name = "tempfile"
version = "0.0.3"
authors = ["Steven Allen <steven@stebalien.com>"]
description = "Securely create temporary files."

documentation = "https://stebalien.github.io/tempfile/tempfile/"
repository = "https://github.com/Stebalien/tempfile"
keywords = ["tempfile", "tmpfile"]
license = "MIT/Apache-2.0"

[dependencies]
libc = "*"
rand = "*"
