[package]
name = "tempfile"
version = "1.0.0"
authors = ["Steven Allen <steven@stebalien.com>"]
description = "Securely create temporary files."

documentation = "https://stebalien.github.io/tempfile/tempfile/"
repository = "https://github.com/Stebalien/tempfile"
keywords = ["tempfile", "tmpfile"]
license = "MIT/Apache-2.0"

[dependencies]
libc = "0.1"
rand = "0.3"
winapi = "0.1"
kernel32-sys = "0.1"
